serverAddr = "server.corneliamo.cn"
serverPort = 10000
webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"

[[proxies]]
name = "http"
type = "tcp"
localIP = "127.0.0.1"
localPort = 10050
remotePort = 10050

