serverAddr = "1.1.1.1"
    serverPort = 9999
    webServer.addr = "127.0.0.1"
    webServer.port = 7400
    webServer.user = "admin"
    webServer.password = "admin"

[[proxies]]
name = "test1
type = "tcp"
localIP = "127.0.0.1"
localPort = 1
remotePort = 1

[[proxies]]
name = "test2
type = "tcp"
localIP = "127.0.0.1"
localPort = 2
remotePort = 2

